[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "voltforge-studio"
version = "0.1.0"
description = "VoltForge Studio MVP for schematic capture, SPICE netlist generation, and Ngspice simulations."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
  { name = "Nikola Stoyanov" }
]
dependencies = [
  "PySide6>=6.7"
]

[project.optional-dependencies]
plot = ["pyqtgraph>=0.13"]
dev = []

[project.scripts]
opencircuitlab = "opencircuitlab.main:main"

[project.urls]
Homepage = "https://github.com/drnecrotix/volt-forge-stodio"
Repository = "https://github.com/drnecrotix/volt-forge-stodio"
Issues = "https://github.com/drnecrotix/volt-forge-stodio/issues"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
